In [142]:
# the goal of this notebook is to create a foundation for tracking hantavirus claims
# the goal of this is not flashy visualization, it is useful awareness of what is happening

In [143]:
import pandas as pd

In [144]:
def extract_state(location_name):

    for state in state_abbrev.keys():
        if state in location_name:
            return state

    return None

In [145]:
# state name (raw dat) to abbreviation (plotly needs) mapping
state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

# Time Series

I want to look at some of these states separately.

In [146]:
data = 'data/verdant_eye/ve_hantavirus_20260513.csv'

tsdf = pd.read_csv(data)
tsdf.columns = ['location', 'date', 'count']
tsdf.head()

# this is not usa data, so I'm changing things from previous analysis

        location        date  count
0         Europe  2026-05-13     38
1         France  2026-05-13     20
2  North America  2026-05-13     29
3         Mexico  2026-05-13      3
4        Jalisco  2026-05-13      1

In [147]:
# tsdf['state'] = tsdf['state'].apply(extract_state)

# tsdf = tsdf.dropna(subset=['state'])

# tsdf = (
#     tsdf.groupby(['state', 'date'])['count']
#     .sum()
#     .reset_index()
# )

# tsdf = tsdf.sort_values('count', ascending=False)

# tsdf = tsdf.reset_index(drop=True)
# tsdf.head()

In [148]:
tsdf.shape

(374, 3)

In [149]:
pvt_df = pd.pivot_table(tsdf, values='count', index='location', columns='date' ).fillna(0).astype(int)

pvt_df = pvt_df.T
pvt_df.index = pd.to_datetime(pvt_df.index)

pvt_df.head()

# we are using location instead of state; there is more noise in 'location' as it is a catch-all which
# gets combined/cleaned downstream. it is easier to cut/combine than to add.

location,12 countries,5 countries,Africa,America,American,Americans,Amsterdam,América del Norte,Andes,Apeldoorn,...,Vesuvian area,Virginia,"Washington, D.C.",Western Australia,Western Cape,Winnebago County,World,Zurich,four states,multiple countries
date,,,,,,,,,,,,,,,,,,,,,
2026-05-03,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2026-05-04,0,0,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2026-05-05,0,0,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2026-05-06,0,0,2,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2026-05-07,0,1,7,0,0,0,1,0,0,0,...,0,2,1,0,0,0,0,0,0,1

In [150]:
# import seaborn as sns
# import matplotlib.pyplot as plt

# plt.figure(figsize=(60, 40))
# sns.heatmap(pvt_df, annot=True, cmap='Blues', linewidths=0.5, cbar=False, annot_kws={"size": 8})
# plt.title('ICE Chatter Counts by State and Date')
# plt.show()

# # wanted to try seaborn approach from https://100daysofnetworks.substack.com/p/day-39-of-100daysofnetworks
# # not interactive, less useful, but visually useful

# Today's Investigation Questions

- What can we learn? I don't have any real goals. OSINT starts with a) a topic that is annoying your mind, b) a query, c) a dataset, and then insights follow. This is not typical data science where you roughly know what is in the data before you start. That is why the first word on my book's subtitle on the cover is EXPLORE, not USE or PREDICT.

In [151]:
pvt_df.head()

location,12 countries,5 countries,Africa,America,American,Americans,Amsterdam,América del Norte,Andes,Apeldoorn,...,Vesuvian area,Virginia,"Washington, D.C.",Western Australia,Western Cape,Winnebago County,World,Zurich,four states,multiple countries
date,,,,,,,,,,,,,,,,,,,,,
2026-05-03,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2026-05-04,0,0,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2026-05-05,0,0,8,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2026-05-06,0,0,2,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2026-05-07,0,1,7,0,0,0,1,0,0,0,...,0,2,1,0,0,0,0,0,0,1

In [152]:
pvt_df.describe()

location,12 countries,5 countries,Africa,America,American,Americans,Amsterdam,América del Norte,Andes,Apeldoorn,...,Vesuvian area,Virginia,"Washington, D.C.",Western Australia,Western Cape,Winnebago County,World,Zurich,four states,multiple countries
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,...,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000
mean,0.090909,0.090909,2.909091,0.181818,0.090909,0.272727,0.090909,0.090909,0.545455,0.090909,...,0.090909,0.363636,0.090909,0.181818,0.090909,0.090909,0.090909,0.090909,0.090909,0.090909
std,0.301511,0.301511,3.113023,0.404520,0.301511,0.646670,0.301511,0.301511,0.934199,0.301511,...,0.301511,0.674200,0.301511,0.603023,0.301511,0.301511,0.301511,0.301511,0.301511,0.301511
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,4.500000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,8.000000,1.000000,1.000000,2.000000,1.000000,1.000000,3.000000,1.000000,...,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [153]:
row_sums = pvt_df.sum(axis=1)
row_sums = row_sums.sort_index(ascending=False)
print(row_sums.reset_index())

         date    0
0  2026-05-13  181
1  2026-05-12  209
2  2026-05-11  388
3  2026-05-10  268
4  2026-05-09  160
5  2026-05-08   54
6  2026-05-07  223
7  2026-05-06  119
8  2026-05-05   58
9  2026-05-04   45
10 2026-05-03   21

In [154]:
# top places
col_sums = pvt_df.sum(axis=0)
col_sums = col_sums.sort_values(ascending=False)
print(col_sums.head(10))

location
Europe            294
North America     266
United States     228
Spain             142
Canary Islands     77
France             52
Tenerife           41
United Kingdom     38
Nebraska           36
South America      34
dtype: int64

Insights so far:
- Some days have more activity than others
- Activity seems to be increasing, but the last two days had less; we'll keep tracking
- Most chatter is mentioning Europe, then North America and USA, then Spain
- Top continents: Europe, then USA
- Top countries: United States, Spain, Canary Islands, France, United Kingdom
- Top city: Tenerife
- Top state: Nebraska

Ok, each one of these is a thread to pull on.

# Let's use World AI to Understand - Verdant Eye API

I'll use my World AI to try to understand what is happening. It takes natural language as input and returns a dataset, which is ideal for AI Agents that need world awareness.

In [155]:
def ask_api(client, question):

    answer = client.predict(question=question, api_name="/predict")
    
    answer = ast.literal_eval(answer)

    return answer

In [156]:
from gradio_client import Client   # for api use

import ast                         # for text to list conversion (make data useful)
import pandas as pd                # for easy data use; you can use polars or whatever you like

token = '../api_creds/vi_key_1.csv'

# load my key
df = pd.read_csv(token) # easy and lazy lol; using pandas anyway ;p
api_key = df['key'][0]  # easy and lazy lol; using pandas anyway ;p

# connect to api
client = Client("verdantintel/verdanteye", token=api_key)

Loaded as API: https://verdantintel-verdanteye.hf.space

# List of DataFrames

I want to shove everything into one dataframe so that I can more easily understand what is happening. I will make it so that data is combined but useful.

In [157]:
dfs = []

# Continents

In [158]:
question = 'what happened in Europe in regards to hantavirus?'

answer = ask_api(client, question)
len(answer)

294

In [159]:
check_df = pd.DataFrame(answer)
check_df.head()

,claim,url,domain,url_domain,date_added
0,"A hantavirus outbreak has expanded, with a Fre...",https://san.com/cc/hantavirus-outbreak-grows-t...,san.com,san.com,2026-05-13 22:00:02
1,Update on hantavirus cases in France.,https://fr.headtopics.com/news/hantavirus-les-...,headtopics.com,fr.headtopics.com,2026-05-13 21:36:07
2,There is a hantavirus outbreak reaching 11 inf...,https://laopinion.com/2026/05/13/brote-de-hant...,laopinion.com,laopinion.com,2026-05-13 21:16:11
3,A British individual was found in an Italian b...,https://metro.co.uk/2026/05/13/hantavirus-brit...,metro.co.uk,metro.co.uk,2026-05-13 21:05:03
4,Among the 22 French contact cases of hantaviru...,https://fr.headtopics.com/news/hantavirus-parm...,headtopics.com,fr.headtopics.com,2026-05-13 19:27:19

In [160]:
# add to list of dataframes

data = {
    "location": "Europe",
    "type": "continent",
    "df": check_df,
}
dfs.append(data)

In [161]:
question = 'what happened in North America in regards to hantavirus?'

answer = ask_api(client, question)
len(answer)

269

In [162]:
check_df = pd.DataFrame(answer)
check_df.head()

,claim,url,domain,url_domain,date_added
0,American monitored for hantavirus and prepared...,https://www.cbsnews.com/video/american-monitor...,cbsnews.com,cbsnews.com,2026-05-14 00:00:39
1,An Oregon doctor is in quarantine after caring...,https://katu.com/news/local/oregon-doctor-step...,katu.com,katu.com,2026-05-13 23:54:31
2,Ontario health officials are monitoring additi...,https://news.ssbcrack.com/ontario-health-offic...,news.ssbcrack.com,news.ssbcrack.com,2026-05-13 22:59:29
3,Hantavirus outbreak linked to a cruise ship an...,https://newsday.com/news/nation/hantavirus-hon...,newsday.com,newsday.com,2026-05-13 22:20:17
4,A doctor on a cruise ship has been isolated in...,https://apnews.com/article/hantavirus-hondius-...,apnews.com,apnews.com,2026-05-13 22:11:23

In [163]:
# add to list of dataframes

data = {
    "location": "North America",
    "type": "continent",
    "df": check_df,
}
dfs.append(data)

# States and Countries

In [164]:
question = 'what happened in Nebraska?'

answer = ask_api(client, question)
len(answer)

476

In [165]:
check_df = pd.DataFrame(answer)
check_df = check_df[check_df['claim'].str.contains('virus')]
check_df.head()

,claim,url,domain,url_domain,date_added
0,Hantavirus outbreak linked to a cruise ship an...,https://newsday.com/news/nation/hantavirus-hon...,newsday.com,newsday.com,2026-05-13 22:20:17
1,A doctor on a cruise ship has been isolated in...,https://apnews.com/article/hantavirus-hondius-...,apnews.com,apnews.com,2026-05-13 22:11:23
2,A travel influencer was quarantined in Nebrask...,https://www.boston.com/news/local-news/2026/05...,boston.com,boston.com,2026-05-13 15:47:00
5,A cruise passenger shares their experience of ...,https://www.foxnews.com/health/cruise-passenge...,foxnews.com,foxnews.com,2026-05-13 01:28:14
6,Health officials are monitoring a hantavirus o...,https://www.cbsnews.com/video/health-officials...,cbsnews.com,cbsnews.com,2026-05-12 23:21:14

In [166]:
# add to list of dataframes

data = {
    "location": "Nebraska",
    "type": "state",
    "df": check_df,
}
dfs.append(data)

# Cities

In [167]:
question = 'what happened in Tenerife?'

answer = ask_api(client, question)
len(answer)

72

In [169]:
check_df = pd.DataFrame(answer)
check_df = check_df[check_df['claim'].str.contains('virus')]
check_df.head()

,claim,url,domain,url_domain,date_added
0,Evacuations of people from a hantavirus-affect...,https://apnews.com/video/final-evacuations-of-...,apnews.com,apnews.com,2026-05-12 17:19:06
3,Passengers are disembarking from a cruise ship...,https://euronews.com/video/2026/05/12/final-pa...,euronews.com,euronews.com,2026-05-12 08:35:39
4,A Civil Guard has died related to an outbreak ...,https://www.marca.com/tiramillas/sucesos/2026/...,marca.com,marca.com,2026-05-11 10:36:31
5,The Hantavirus cruise reopens the debate on wh...,https://www.marca.com/tiramillas/politica/2026...,marca.com,marca.com,2026-05-11 10:28:08
7,A Civil Guard has died during the disembarkati...,https://www.marca.com/tiramillas/sucesos/2026/...,marca.com,marca.com,2026-05-11 08:08:15

In [170]:
# add to list of dataframes

data = {
    "location": "Nebraska",
    "type": "state",
    "df": check_df,
}
dfs.append(data)

# Combined DataFrame

Let's explore this combined DataFrame. First, let's merge it into one usable Dataframe.

In [171]:
from datetime import datetime

date_str = datetime.now().strftime("%Y%m%d")
outfile = 'data/verdant_eye/ve_hantavirus_combined_{}.csv'.format(date_str)

for entry in dfs:
    entry["df"]["location"] = entry["location"]
    entry["df"]["type"] = entry["type"]

combined_df = pd.concat([entry["df"] for entry in dfs])
combined_df = combined_df.reset_index(drop=True)
combined_df.to_csv(outfile, index=False)
combined_df.head()

,claim,url,domain,url_domain,date_added,location,type
0,"A hantavirus outbreak has expanded, with a Fre...",https://san.com/cc/hantavirus-outbreak-grows-t...,san.com,san.com,2026-05-13 22:00:02,Europe,continent
1,Update on hantavirus cases in France.,https://fr.headtopics.com/news/hantavirus-les-...,headtopics.com,fr.headtopics.com,2026-05-13 21:36:07,Europe,continent
2,There is a hantavirus outbreak reaching 11 inf...,https://laopinion.com/2026/05/13/brote-de-hant...,laopinion.com,laopinion.com,2026-05-13 21:16:11,Europe,continent
3,A British individual was found in an Italian b...,https://metro.co.uk/2026/05/13/hantavirus-brit...,metro.co.uk,metro.co.uk,2026-05-13 21:05:03,Europe,continent
4,Among the 22 French contact cases of hantaviru...,https://fr.headtopics.com/news/hantavirus-parm...,headtopics.com,fr.headtopics.com,2026-05-13 19:27:19,Europe,continent

# Graph Analysis

Let's first see who is even talking about this topic. What is the landscape? I'll just explore this in cosmograph for now. I'll save a simpler file in a sharable directory so that you all can play with the cosmograph visualization and so that I can share it with the media.

We're not doing centralities and stuff today. We can just look at this with our eyeballs.

In [172]:
date_str = datetime.now().strftime("%Y%m%d")
outfile = 'data/cosmograph/ve_hantavirus_websites_{}.csv'.format(date_str)
edgelist_df = combined_df[['date_added', 'domain', 'url_domain', 'claim']]
edgelist_df.to_csv(outfile, index=False)

In [173]:
# what is happening
# https://cosmograph.app/run/?data=https://raw.githubusercontent.com/itsgorain/100daysofnetworks/refs/heads/main/data/cosmograph/edgelist_hantavirus_20260513.csv&source=source&target=target&gravity=0.25&repulsion=1&repulsionTheta=1.15&linkSpring=1&linkDistance=10&friction=0.85&renderLabels=true&renderHoveredLabel=true&renderLinks=true&nodeSizeScale=1&linkWidthScale=1&linkArrowsSizeScale=1&nodeSize=size-total%20links&nodeColor=color-default&linkWidth=width-default&linkColor=color-default&

# what websites are talking
# https://cosmograph.app/run/?data=https://raw.githubusercontent.com/itsgorain/100daysofnetworks/refs/heads/main/data/cosmograph/ve_hantavirus_websites_20260513.csv&source=domain&target=url_domain&gravity=0.25&repulsion=1&repulsionTheta=1.15&linkSpring=1&linkDistance=10&friction=0.85&renderLabels=true&renderHoveredLabel=true&renderLinks=true&nodeSizeScale=1&linkWidthScale=1&linkArrowsSizeScale=1&nodeSize=size-total%20links&nodeColor=color-default&linkWidth=width-default&linkColor=color-default&

# Sequence of Claims

Finally, let's explore the sequence of events that have happened so far, from top to bottom. This is only a few hundred claims. It won't take forever.

In [174]:
combined_df['date'] = pd.to_datetime(combined_df['date_added']).dt.date
combined_df['time'] = pd.to_datetime(combined_df['date_added']).dt.time
combined_df = combined_df.sort_values('date_added')

for date, group in combined_df.groupby('date'):
    print(f"### {date} ###")
    print()
    for _, row in group.iterrows():
        print(f"  {row['time']} - {row['claim']} ({row['location']})")
    print()

### 2026-05-03 ###

  20:33:22 - A hantavirus outbreak has occurred, causing a British tourist to fight for their life on a cruise ship, with three fatalities reported. (Europe)
  21:02:55 - Suspected hantavirus outbreak on a cruise ship in the US. (North America)
  21:02:55 - Hantavirus outbreak on cruise ship leads to three British deaths. (North America)
  22:31:07 - Multiple deaths due to a suspected hantavirus in the Netherlands (Europe)
  22:53:43 - Three people have died in a suspected hantavirus outbreak on an Atlantic cruise ship. (North America)

### 2026-05-04 ###

  00:48:53 - A suspected outbreak of a rare hantavirus on a cruise ship in the Atlantic Ocean has resulted in the deaths of three people. (North America)
  01:51:39 - A hantavirus outbreak has resulted in the deaths of 3 people on a cruise ship in the Atlantic Ocean, according to WHO. (North America)
  09:01:11 - Symptoms of hantavirus infection have led to the death of three people on a cruise heading to the Canary Islands. (Europe)
  09:55:30 - Hantavirus infection linked to cruise passengers, causing three deaths and one Briton in critical condition. (Europe)
  11:07:46 - A suspected outbreak of a rare hantavirus on a cruise ship in the Atlantic Ocean has resulted in 3 fatalities. (North America)
  11:29:04 - A hantavirus outbreak on a cruise ship has led to a Dutch emergency operation. (Europe)
  15:57:01 - 14 Spaniards aboard the MV Hondius cruise have died, and three people were affected by a hantavirus outbreak. (Europe)
  19:53:03 - Dutch widow died from hantavirus during cruise, leaving 20 Brits trapped (Europe)
  20:43:07 - A Dutch widow died from hantavirus during a cruise, leaving 20 British passengers stranded. (Europe)

### 2026-05-05 ###

  00:29:14 - A hantavirus investigation is underway on a cruise ship in the Atlantic. (North America)
  01:15:31 - Strict measures on board Hondius after hantavirus outbreak (North America)
  05:58:14 - Hantavirus outbreak on a cruise ship in Germany (Europe)
  06:31:06 - An Irish woman is stranded on a cruise ship due to hantavirus. (Europe)
  07:28:53 - There is a hantavirus outbreak linked to a cruise ship in the Canary Islands. (Europe)
  11:15:31 - Cruise ship with hantavirus outbreak headed for the Canary Islands. (Europe)
  11:28:57 - Cruise with hantavirus outbreak received by Spain (Europe)
  11:58:47 - There is a hantavirus outbreak on a cruise ship, with suspected human transmission; Spain allows the ship to dock in the Canary Islands. (Europe)
  14:13:08 - An American stranded on a cruise ship affected by hantavirus is expressing concerns for safety. (North America)
  15:57:56 - Spain requests evacuation of hantavirus cases (Europe)
  16:03:01 - An American blogger's emotional response to a hantavirus video (North America)
  19:16:45 - American speaks about cruise ship experience during hantavirus outbreak. (North America)
  20:41:50 - A Boston travel influencer was linked to a hantavirus outbreak on a cruise ship. (North America)
  21:24:54 - A hantavirus outbreak negatively impacts the Florida cruise industry's image (North America)
  22:11:49 - Spain accepts to receive cruise with hantavirus outbreak. (Europe)

### 2026-05-06 ###

  00:14:19 - A Boston travel influencer is trapped on a cruise ship facing a deadly hantavirus outbreak. (North America)
  04:53:18 - Hantavirus detected on Hondius cruise ship (North America)
  05:48:48 - Suspected hantavirus outbreak on a Dutch cruise ship. (Europe)
  06:50:45 - Alert for hantavirus on Dutch cruise ship (Europe)
  07:58:53 - Hantavirus outbreak linked to a cruise ship in the Canary Islands (Europe)
  08:03:28 - Hantavirus outbreak on Dutch cruise ship with two cases (Europe)
  08:03:28 - Canary Islands refuse to allow cruise ship with hantavirus outbreak to dock (Europe)
  08:59:34 - A patient infected with hantavirus in Switzerland is currently isolated. (Europe)
  08:59:34 - The first hantavirus case in Switzerland has occurred after a trip to South America. (Europe)
  08:59:34 - The first hantavirus case in Switzerland has been reported involving a man in Zurich. (Europe)
  10:09:14 - Canary Islands government denounces misinformation from the Spanish government regarding a cruise and hantavirus cases. (Europe)
  10:17:16 - Hantavirus cruise ship turned away from Canary Islands. (Europe)
  10:24:59 - The hantavirus sparks a political battle between the government and the Canary Islands (Europe)
  10:30:21 - WHO reports that three suspected hantavirus patients were evacuated from a cruise ship to the Netherlands. (Europe)
  10:53:57 - New case of hantavirus reported on a cruise ship in the Canary Islands linked to Switzerland (Europe)
  11:11:06 - Patients with hantavirus evacuated to the Netherlands as cruise ship heads to Spain. (Europe)
  11:32:12 - Hantavirus has reached Europe, and there is a first patient reported. (Europe)
  11:33:07 - Three patients were evacuated from a cruise ship due to a hantavirus outbreak, with a new case confirmed in Switzerland. (Europe)
  11:51:27 - A hantavirus outbreak has led to the evacuation of patients from a cruise ship, with a new case confirmed in Switzerland. (Europe)
  12:20:16 - A Swiss man has tested positive for hantavirus after returning from a cruise associated with a deadly outbreak. (Europe)
  13:09:08 - The vessel Hondius sails towards the Canary Islands due to hantavirus (Europe)
  13:09:08 - The 14 Spaniards on board the cruise affected by hantavirus (Europe)
  13:09:08 - The vessel Hondius sails towards the Canary Islands due to hantavirus (North America)
  13:13:34 - Three patients are being evacuated to Europe from a cruise ship due to a hantavirus outbreak. (Europe)
  13:31:39 - A hantavirus case has been confirmed in Switzerland, raising concerns about human-to-human transmission. (Europe)
  14:13:10 - New case of hantavirus reported linked to cruise ship in the Canary Islands. (Europe)
  14:28:10 - Three patients are being evacuated to Europe due to a hantavirus outbreak on a cruise ship. (Europe)
  14:40:21 - A cruise ship carrying hantavirus cases is docking in Granadilla, Canary Islands, according to the Spanish health minister. (Europe)
  14:55:25 - Hantavirus outbreak on a cruise ship in Spain. (Europe)
  14:57:00 - There has been an outbreak of hantavirus on a cruise ship, with another case reported in Switzerland. (Europe)
  15:29:01 - Spain allows hantavirus-affected cruise ship to dock (Europe)
  16:35:49 - Spain will receive a cruise affected by a hantavirus outbreak to evacuate passengers. (Europe)
  17:30:53 - Hantavirus causing fear from New Mexico tragedy (North America)
  17:50:20 - Mapping hantavirus cases in the US (North America)
  18:05:32 - A cruise ship associated with a deadly hantavirus outbreak is setting sail for the Spanish Islands. (Europe)
  18:25:35 - Hantavirus outbreak spreads to Europe linked to a cruise passenger. (Europe)
  18:53:07 - A cruise with passengers confined due to hantavirus is heading to the Canary Islands while the whereabouts of 23 others are lost. (Europe)
  20:07:04 - Three patients are being evacuated to Europe due to a hantavirus outbreak on a cruise ship. (Europe)
  20:25:26 - The President of the Canary Islands confronts the Madrid government and refuses to accept the cruise ship with hantavirus. (Europe)
  20:44:21 - Brits may have hantavirus after cruise ship incident (Europe)
  20:52:47 - Hantavirus patients from a cruise ship are arriving in Europe for treatment. (Europe)
  21:04:07 - A cruise ship with a hantavirus outbreak is heading to the Canary Islands after three people were evacuated. (Europe)
  23:15:15 - Spain evacuates passengers from a cruise ship with hantavirus (Europe)
  23:56:00 - There was a hantavirus outbreak on a cruise ship linked to the Hondius. (North America)

### 2026-05-07 ###

  01:20:36 - There is a hantavirus outbreak involving U.S. cruise passengers. (North America)
  01:48:53 - Brits are self-isolating due to hantavirus concerns. (Europe)
  04:44:26 - Contact person for hantavirus arrives at Düsseldorf clinic. (Europe)
  05:20:51 - Georgia is monitoring two residents after a hantavirus case on a cruise. (North America)
  05:44:47 - A British passenger has been infected with hantavirus and speaks about their experience. (Europe)
  05:59:25 - Health operation for the hantavirus outbreak on a cruise ship arriving in the Canary Islands. (Europe)
  07:00:11 - A hantavirus outbreak linked to a cruise ship involving Switzerland and Argentina. (Europe)
  07:00:11 - A hantavirus outbreak reported on a cruise ship in Tenerife, Canary Islands. (Europe)
  07:00:11 - A hantavirus outbreak reported on a cruise ship in Tenerife, Canary Islands. (Nebraska)
  07:17:39 - Advice and information on hantavirus risk for Americans related to the MV Hondius (North America)
  07:19:19 - A French contact case of hantavirus, what we know (Europe)
  08:37:22 - A flight attendant has been hospitalized due to hantavirus after a cruise ship, infected with the virus, is near the Canary Islands. (Europe)
  08:51:18 - Hantavirus outbreak among cruise ship passengers in the UK (Europe)
  09:13:27 - A cruise ship with a hantavirus outbreak is heading to the Canary Islands after three passengers were evacuated. (Europe)
  09:20:25 - There is chaos in Europe due to an increase in hantavirus cases. (Europe)
  10:01:39 - Potential hantavirus carriers from a cruise ship could spread the virus globally, affecting passengers from multiple countries. (Europe)
  10:01:39 - Potential hantavirus carriers from a cruise ship could spread the virus globally, affecting passengers from multiple countries. (North America)
  10:21:46 - A flight attendant has been hospitalized due to hantavirus infection from a cruise near the Canary Islands. (Europe)
  10:21:46 - A flight attendant has been hospitalized due to hantavirus infection from a cruise near the Canary Islands. (Europe)
  10:21:46 - A flight attendant has been hospitalized due to hantavirus infection from a cruise near the Canary Islands. (Europe)
  10:40:55 - A French cruise passenger has contracted hantavirus. (Europe)
  10:40:55 - A flight attendant has been isolated due to a hantavirus outbreak in Amsterdam. (Europe)
  10:59:30 - Hantavirus is a concern in the US (North America)
  11:04:37 - The US is monitoring a hantavirus case related to cruise passengers and a flight attendant. (North America)
  11:36:34 - Officials are racing to trace the contacts of hantavirus victims on a cruise ship heading to Spain's Canary Islands. (Europe)
  11:57:42 - Officials are attempting to trace victims and contacts related to a hantavirus outbreak linked to a cruise ship in Spain's Canary Islands. (Europe)
  12:19:02 - California, Colorado, New Mexico, and Arizona are at risk of hantavirus and the means of transmission are discussed. (North America)
  12:44:27 - California is monitoring residents who were aboard a hantavirus cruise ship. (North America)
  12:45:19 - A hantavirus outbreak on a cruise ship is under global monitoring, with the U.S. concerned about cases in Arizona and Georgia. (North America)
  13:02:16 - Port workers in Granadilla threaten to block facilities when a cruise ship with a hantavirus outbreak arrives. (Europe)
  13:10:04 - California is monitoring residents who were aboard a hantavirus cruise ship. (North America)
  13:28:55 - There is a possible hantavirus case involving a KLM flight attendant being investigated in the Netherlands. (Europe)
  13:30:35 - Spain is disclosing health protocol details for an impending hantavirus outbreak related to a ship. (Europe)
  14:18:40 - Georgia, Arizona, and California are monitoring possible hantavirus cases after an outbreak on the MV Hondius (North America)
  14:20:12 - Rats on cruise ship spread hantavirus to the UK (Europe)
  14:36:12 - Americans who were on a hantavirus-infected cruise ship are returning home to three states. (North America)
  14:55:40 - The US is monitoring a hantavirus outbreak related to a polar cruise vessel. (North America)
  15:12:47 - There are hantavirus cases related to cotton rats in Florida and advice on how to protect yourself. (North America)
  15:19:24 - Two Canadian passengers from a hantavirus cruise are in Ontario (North America)
  15:33:29 - Virginia is the fourth state to initiate monitoring for hantavirus (North America)
  15:33:29 - Update on British passengers from hantavirus cruise ship (Europe)
  16:11:46 - Rep. Janelle Bynum is urging federal assistance for Americans affected by a hantavirus outbreak on a ship. (North America)
  16:28:57 - Government reports that 3 Canadians are isolating at home due to a hantavirus outbreak. (North America)
  16:44:09 - The WHO stated that the hantavirus outbreak does not signify the start of a pandemic following 5 confirmed cases on a cruise ship heading to Spain. (Europe)
  16:44:09 - California and two other states are monitoring residents after a hantavirus outbreak on a cruise ship. (North America)
  16:50:30 - Government reports that 3 Canadians are isolating at home after a hantavirus outbreak on a ship. (North America)
  16:53:29 - Hantavirus outbreak associated with a cruise ship heading to Spain's Canary Islands, with officials racing to trace victims' contacts. (Europe)
  17:23:57 - Tenerife locals are concerned but calm about hantavirus-affected cruise ship. (Europe)
  17:23:57 - Tenerife locals are concerned but calm about hantavirus-affected cruise ship. (Nebraska)
  17:29:55 - California and three states are monitoring residents who were on the cruise affected by hantavirus. (North America)
  17:33:42 - There is a hantavirus threat in NYC that residents should be aware of. (North America)
  17:48:56 - A Bend doctor is involved in a cruise ship outbreak of hantavirus. (North America)
  17:50:09 - A hantavirus outbreak linked to a cruise ship has resulted in a traveler death in Virginia. (North America)
  17:50:09 - Two Georgia residents are being monitored after leaving a cruise ship associated with a deadly hantavirus outbreak. (North America)
  17:56:05 - Deadly hantavirus concerns and questions in the USA (North America)
  17:56:05 - Hantavirus presence in the Washington DC area (North America)
  17:56:05 - Possible spread of hantavirus in NYC (North America)
  18:29:47 - Two Texans exposed to hantavirus on a cruise ship have reported their situation to health officials. (North America)
  19:34:32 - Information about hantavirus in Philadelphia (North America)
  19:44:34 - A hantavirus outbreak in Texas has affected two individuals connected to a cruise. (North America)
  19:52:50 - 3 Canadians are isolating at home due to a hantavirus outbreak on a ship. (North America)
  19:57:09 - Two Texas residents were on a cruise ship with a hantavirus outbreak. (North America)
  19:58:05 - Two residents in Georgia are being monitored for hantavirus after being on a cruise ship. (North America)

### 2026-05-08 ###

  08:04:08 - U.S. health officials monitoring cruise passengers after hantavirus outbreak (North America)
  08:04:08 - California residents at risk due to hantavirus outbreak on cruise ship (North America)
  08:04:08 - Report on hantavirus outbreak linked to a cruise ship in California (North America)
  08:10:38 - Live updates on US cases and deaths related to the hantavirus outbreak. (North America)
  08:31:21 - Exploring the potential of hantavirus to become a significant health threat like COVID-19 and assessing the U.S. response. (North America)
  09:02:14 - Isolation measures in Spain amid hantavirus outbreak and COVID-19. (Europe)
  09:12:51 - Third Briton feared to have hantavirus in remote inhabited island (Europe)
  09:14:24 - Two Texas residents were on a cruise ship affected by a hantavirus outbreak according to the CDC. (North America)
  09:37:46 - Spain is preparing for evacuations in response to a hantavirus outbreak. (Europe)
  09:47:14 - Spain is preparing for evacuations due to a hantavirus outbreak on a cruise ship. (Europe)
  10:23:27 - A hantavirus outbreak on a cruise ship is raising concerns, with San Diego County tracking cases this year. (North America)
  10:48:08 - A Bend doctor is on a cruise ship that is at the center of a hantavirus outbreak. (North America)
  10:49:33 - Spain prepares for evacuations related to a hantavirus outbreak on a cruise ship. (Europe)
  10:54:43 - Spain is preparing evacuations related to a hantavirus outbreak classified as a level 3 emergency by the CDC. (Europe)
  10:56:58 - There is a hantavirus outbreak that the CDC has classified as a level 3 emergency response, leading to evacuations in Spain. (Europe)
  11:18:13 - Hantavirus outbreak classified as a Level 3 emergency by the CDC with evacuations in Spain (Europe)
  11:37:09 - Spain is preparing for evacuations due to a hantavirus outbreak on a cruise ship heading for the Canary Islands. (Europe)

### 2026-05-09 ###

  15:01:16 - Hantavirus exposure case in Rome (Europe)
  15:05:54 - New Jersey health officials are monitoring two residents for potential hantavirus exposure. (North America)
  15:06:01 - World health chief addresses concerns of Tenerife residents regarding hantavirus. (Europe)
  15:06:01 - World health chief addresses concerns of Tenerife residents regarding hantavirus. (Nebraska)
  15:14:09 - Britons are reportedly trapped on a cruise ship in Tenerife due to hantavirus concerns. (Europe)
  15:14:09 - Britons are reportedly trapped on a cruise ship in Tenerife due to hantavirus concerns. (Nebraska)
  15:16:11 - Hantavirus outbreak linked to a cruise ship in Spain. (Europe)
  15:20:49 - A Californian has returned home after being on a cruise affected by hantavirus. (North America)
  15:24:20 - Spain is preparing to dock a cruise ship affected by hantavirus to evacuate passengers. (Europe)
  15:24:20 - A ship with a hantavirus outbreak is heading toward the Canary Islands, prompting local protests. (Europe)
  15:24:20 - Americans evacuated from a cruise ship due to a hantavirus outbreak. (North America)
  15:26:26 - Report on growing hantavirus outbreak in Canada (North America)
  15:32:08 - Tenerife residents express fury over hantavirus concerns as a cruise ship disembarks British passengers. (Nebraska)
  15:32:08 - Tenerife residents express fury over hantavirus concerns as a cruise ship disembarks British passengers. (Europe)
  15:38:39 - Two New Jersey residents are being monitored for potential hantavirus exposure related to a cruise ship. (North America)
  15:43:10 - Globalists are allegedly initiating 'COVID 2.0' as hantavirus spreads, prompting EU mask recommendations. (Europe)
  15:45:42 - New plan to evacuate Americans from hantavirus cruise. (North America)
  15:59:33 - Report on a woman in Florence quarantined after flying with a hantavirus victim. (Europe)
  16:11:52 - Americans facing quarantine due to hantavirus in Nebraska. (Nebraska)
  16:11:52 - Americans facing quarantine due to hantavirus in Nebraska. (North America)
  16:11:52 - Discussion about U.S. plans regarding a hantavirus cruise ship outbreak. (North America)
  16:20:02 - The most controversial port in the Canary Islands presents itself for the hantavirus cruise landing. (Europe)
  16:45:14 - Cruise passengers with hantavirus will be quarantined in Nebraska. (Nebraska)
  16:45:14 - Cruise passengers with hantavirus will be quarantined in Nebraska. (North America)
  16:54:56 - Americans are being monitored due to a hantavirus outbreak linked to a cruise ship. (North America)
  17:01:01 - The head of WHO is reassuring residents regarding a ship carrying hantavirus headed for Spanish Island. (Europe)
  17:15:36 - Concerns about the potential danger of a hantavirus outbreak in Tenerife. (Europe)
  17:15:36 - Concerns about the potential danger of a hantavirus outbreak in Tenerife. (Nebraska)
  17:39:33 - LA health officials are monitoring hantavirus reports linked to a cruise ship outbreak. (North America)