In [11]:
import wikipedia as w
import pandas as pd

from time import sleep

# Wikipedia Edgelist Generator

Feel free to use this Wikipedia edgelist generator for your own research uses. However, please keep a few things in mind.
- For the function 'create_edgelist_df', the default iterations has been set to 2, and I did 4 for this example. The higher the number, the more you will query the Wikipedia API. Even at 4, we ended up with a network of 9,000+ nodes, so don't go overboard. Use this responsibly. Start at 2, check the results, if you need more increase to 3, check results, etc.
- No matter what, do include a sleep() command. I have it set to 0.3 seconds between each search. A higher number will be better but take longer.
- Always crawl responsibly. If you are too aggressive, your IP will be blocked by Wikipedia and you will get nothing.
- Check the day_5_analysis notebook to see how the data can be used.

In [12]:
def search_wiki(search_list):

    origin_pages = []
    found_pages = []

    # later, we will drop these to keep the properly named page in the network

    for search in search_list:

        print('searching topic: {}'.format(search))
        
        try:
            #page = w.page(search)
            #search_results = page.links
            search_results = w.search(search)

            for found_page in search_results:

                origin_pages.append(search)
                found_pages.append(found_page)

        except:
            
            print('not found')
            
        sleep(0.3)
        
    return origin_pages, found_pages

In [13]:
def create_edgelist_df(seed_searches, iterations=2):

    completed = []
    sources = []
    targets = []

    for i in range(iterations):
        
        print('starting iteration: {}'.format(i))
        print()

        if i == 0:

            search_list = seed_searches

        origin_pages, found_pages = search_wiki(search_list)

        completed.extend(origin_pages)
        sources.extend(origin_pages)
        targets.extend(found_pages)

        search_list = sorted(set([t for t in targets if t not in completed]))
        print(len(search_list))
        print()
        print(search_list)
        print()
        
    df = pd.DataFrame(list(zip(sources, targets)))
    df.columns = ['source', 'target']
                  
    return df

In [14]:
seed_searches = ['Lily Seabird']

df = create_edgelist_df(seed_searches, iterations=2) # keep it low (1-3) or this will take forever

starting iteration: 0

searching topic: Lily Seabird
9

['Burnover', 'Desertas Islands', 'End of the Road Festival', 'Lame-O Records', "Lily's Driftwood Bay", 'Lincoln Park Zoo', 'List of 2025 albums', 'List of 2026 albums', 'New England Music Awards']

starting iteration: 1

searching topic: Burnover
searching topic: Desertas Islands
searching topic: End of the Road Festival
searching topic: Lame-O Records
searching topic: Lily's Driftwood Bay
searching topic: Lincoln Park Zoo
searching topic: List of 2025 albums
searching topic: List of 2026 albums
searching topic: New England Music Awards
74

['2008 MTV Europe Music Awards', '2026 United States wildfires', '2026 in animation', 'An Horse', 'Annette Crosbie', "Ardal O'Hanlon", 'Bugio Island', 'Circuit des Yeux', 'Colin Williams (producer)', 'Deserta Grande Island', 'Emergency vehicle lighting', 'End of the Road', 'End of the Road World Tour', 'Escape fire', 'GA-20', 'Gallipoli: End of the Road', 'Gladie', 'Greg Freeman (musician)', 'Hogna ingens', 'Hurry (band)', 'Ilhéu Chão', 'It Ends', 'Jane Horrocks', 'Joanna Newsom', 'John Henry (folklore)', 'Lincoln Park', 'Lincoln Park (Chicago community area)', 'Lincoln Park Zoo (Manitowoc)', 'List of 2022 albums', 'List of Billboard 200 number-one albums of 2025', 'List of Billboard 200 number-one albums of 2026', 'List of Malayalam films of 2026', 'List of UK top-ten albums in 2026', 'List of albums containing a hidden track', 'List of best-selling albums', 'List of best-selling albums in the United Kingdom', 'List of best-selling albums in the United States', 'List of best-selling albums of the 21st century', 'List of fastest-selling albums', 'List of reptiles of Madeira', 'List of zoo escapes', 'Madeira', 'Madeira evergreen forests', 'Marietta (band)', 'Mo Troper', 'Modern Baseball', 'Mossuril District', 'Nature Boardwalk', 'New England', 'New England Conservatory of Music', 'New Order (band)', 'Oklahoma City Zoo and Botanical Garden', 'PEN New England Award', 'Peter Mullan', 'Pico Ruivo', 'Richard Dormer', 'Rocky (bear)', 'Rozi Plain', 'Sean McLaughlin (music producer)', 'Sergeant Siwash', 'Sixteen South', 'Slaughter Beach, Dog', 'Snyder Fire', 'Sports (Modern Baseball album)', 'Stephen Fry bibliography and filmography', 'The Beatles albums discography', 'The Elovaters', 'The Felice Brothers', 'The Lost Bus (soundtrack)', 'Uninhabited island', 'Virgin (Lorde album)', 'Wildfire suppression', 'William Orbit', 'Zoo Parade']

In [15]:
df.shape

(100, 2)

In [16]:
df.head() # 2026 albums useful for GrooveSeeker

         source                    target
0  Lily Seabird              Lily Seabird
1  Lily Seabird       List of 2026 albums
2  Lily Seabird       List of 2025 albums
3  Lily Seabird                  Burnover
4  Lily Seabird  End of the Road Festival

In [17]:
outfile = 'data/lilyseabird.csv'

df.to_csv(outfile, index=False)

In [18]:
# verify the outfile looks good

df = pd.read_csv(outfile)
df.head()

         source                    target
0  Lily Seabird              Lily Seabird
1  Lily Seabird       List of 2026 albums
2  Lily Seabird       List of 2025 albums
3  Lily Seabird                  Burnover
4  Lily Seabird  End of the Road Festival

In [19]:
df.shape

(100, 2)